-- Run with LBACSYS Permission
GRANT EXECUTE ON sa_components TO courseman WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO courseman WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO courseman WITH GRANT OPTION;
GRANT EXECUTE ON sa_label_admin TO courseman WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO courseman WITH GRANT OPTION;
GRANT EXECUTE ON sa_audit_admin  TO courseman WITH GRANT OPTION;

GRANT LBAC_DBA TO courseman;
GRANT EXECUTE ON sa_sysdba TO courseman;
GRANT EXECUTE ON to_lbac_data_label TO courseman

-- Run as Courseman

BEGIN
  SA_SYSDBA.DROP_POLICY(
    policy_name => 'COURSEMAN_ACCESS_LICH_HOC');
END;

BEGIN
  SA_SYSDBA.CREATE_POLICY(
  policy_name => 'COURSEMAN_ACCESS_LICH_HOC', 
  column_name => 'POLICY_LABEL');
END;

GRANT COURSEMAN_ACCESS_LICH_HOC_DBA TO COURSEMAN;

-- Tao level
EXEC SA_COMPONENTS.CREATE_LEVEL('COURSEMAN_ACCESS_LICH_HOC', 80, 'TPK', 'Truong pho khoa');
EXEC SA_COMPONENTS.CREATE_LEVEL('COURSEMAN_ACCESS_LICH_HOC', 60, 'TBM', 'Truong bo mon');
EXEC SA_COMPONENTS.CREATE_LEVEL('COURSEMAN_ACCESS_LICH_HOC', 40, 'GV', 'Giao vien');
EXEC SA_COMPONENTS.CREATE_LEVEL('COURSEMAN_ACCESS_LICH_HOC', 20, 'SV', 'Sinh vien');

-- Tao compartment
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('COURSEMAN_ACCESS_LICH_HOC', 100, 'HTTT', 'He thong thong tin');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('COURSEMAN_ACCESS_LICH_HOC', 200, 'KTPM', 'Ky thuat phan mem');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('COURSEMAN_ACCESS_LICH_HOC', 300, 'KHMT', 'Khoa hoc may tinh');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('COURSEMAN_ACCESS_LICH_HOC', 400, 'HS', 'Hoa sinh');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('COURSEMAN_ACCESS_LICH_HOC', 500, 'HHCHD', 'Hoa huu co Hoa dau');

-- Tao group
EXEC SA_COMPONENTS.CREATE_GROUP('COURSEMAN_ACCESS_LICH_HOC', 100, 'CNTT', 'Cong nghe thong tin', NULL);
EXEC SA_COMPONENTS.CREATE_GROUP('COURSEMAN_ACCESS_LICH_HOC', 200, 'HOA', 'Hoa', NULL);

CREATE OR REPLACE FUNCTION FN_GET_TEN_BO_MON(
  p_ma_mon_hoc_mo IN NUMBER
) RETURN VARCHAR2
AS
  v_ten VARCHAR2(100);
BEGIN
  SELECT TEN_BO_MON 
  INTO v_ten
  FROM BO_MON
  WHERE MA_BO_MON = (
    SELECT MA_BO_MON FROM MON_HOC
    WHERE MA_MON_HOC = (
      SELECT MA_MON_HOC FROM MON_HOC_MO
      WHERE MA_MON_HOC_MO = p_ma_mon_hoc_mo
    )
  );
  
  RETURN v_ten;
END;
/

CREATE OR REPLACE FUNCTION FN_GET_TEN_KHOA(
  p_ma_mon_hoc_mo IN NUMBER
) RETURN VARCHAR2
AS
  v_ten VARCHAR2(100);
BEGIN
  SELECT TEN_KHOA 
  INTO v_ten
  FROM KHOA
  WHERE MA_KHOA = (
    SELECT MA_KHOA FROM BO_MON
    WHERE MA_BO_MON = (
      SELECT MA_BO_MON FROM MON_HOC
      WHERE MA_MON_HOC = (
        SELECT MA_MON_HOC FROM MON_HOC_MO
        WHERE MA_MON_HOC_MO = p_ma_mon_hoc_mo
      )
    )
  );
  RETURN v_ten;
END;
/

CREATE OR REPLACE FUNCTION FN_GET_LICH_HOC_LABEL (
  p_ma_mon_hoc_mo NUMBER)
RETURN LBACSYS.LBAC_LABEL AS
  v_khoa VARCHAR2(30);
  v_bo_mon VARCHAR2(30);
BEGIN
  v_bo_mon := FN_GET_TEN_BO_MON(p_ma_mon_hoc_mo);
  v_khoa := FN_GET_TEN_KHOA(p_ma_mon_hoc_mo);
  RETURN TO_LBAC_DATA_LABEL('COURSEMAN_ACCESS_LICH_HOC','SV:' || v_bo_mon || ':' || v_khoa);
END;
/

BEGIN
  SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('COURSEMAN_ACCESS_LICH_HOC','COURSEMAN','LICH_HOC');
END;

BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    policy_name => 'COURSEMAN_ACCESS_LICH_HOC',
    schema_name => 'COURSEMAN',
    table_name  => 'LICH_HOC',
    table_options => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL',
    label_function => 'COURSEMAN.FN_GET_LICH_HOC_LABEL(:new.MA_MON_HOC_MO)',
    predicate => NULL);
END;
/

BEGIN
  SA_USER_ADMIN.SET_USER_PRIVS('COURSEMAN_ACCESS_LICH_HOC','CE_GIAOVU','FULL,PROFILE_ACCESS');
  SA_USER_ADMIN.SET_USER_PRIVS('COURSEMAN_ACCESS_LICH_HOC','COURSEMAN','FULL,PROFILE_ACCESS');
END;
COMMIT;

UPDATE COURSEMAN.LICH_HOC
SET THUTRONGTUAN = THUTRONGTUAN;

-- In our system, Ministry can open new course in a semester and they can also view
-- So we will grant full profile access to ministry

GRANT SELECT ON COURSEMAN.LICH_HOC TO PUBLIC;
GRANT INSERT ON COURSEMAN.LICH_HOC TO PUBLIC;

SELECT NGUOI_DUNG.USERNAME, BO_MON.TEN_BO_MON FROM NGUOI_DUNG, BO_MON
WHERE KIEUND = 2
AND NGUOI_DUNG.MA_ND = BO_MON.MA_TBM;


BEGIN
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_VOBICHXA','TPK:KHMT,HTTT,KTPM:CNTT');
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_LEXUANAN','TBM:KTPM:CNTT');
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_TRANHANHUNG','TBM:KHMT:CNTT');
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_HODONGXA','TPK:HTTT:CNTT');
END;
/

BEGIN
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_NGUYENKIMXA','TPK:HHCHD,HS:HOA');
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_BUIMANHAN','TBM:HHCHD:HOA');
  SA_USER_ADMIN.SET_USER_LABELS('COURSEMAN_ACCESS_LICH_HOC','CE_DUONGBAMAO','TBM:HS:HOA');
END;
/

COMMIT;