-- Create all necessary roles for the running system
CREATE ROLE GIAOVIEN;
CREATE ROLE GIAOVU;
CREATE ROLE SINHVIEN;
CREATE ROLE TRUONGPHOKHOA;
CREATE ROLE TRUONGBOMON;

GRANT GIAOVIEN TO TRUONGPHOKHOA;
GRANT GIAOVIEN TO TRUONGBOMON;

GRANT CREATE USER TO GIAOVU;

GRANT SELECT ON COURSEMAN.NGUOI_DUNG TO SINHVIEN;
GRANT SELECT ON COURSEMAN.NGUOI_DUNG TO GIAOVU;
GRANT SELECT ON COURSEMAN.NGUOI_DUNG TO GIAOVIEN;

GRANT SELECT ON COURSEMAN.LUU_KEY TO SINHVIEN;
GRANT SELECT ON COURSEMAN.LUU_KEY TO GIAOVU;
GRANT SELECT ON COURSEMAN.LUU_KEY TO GIAOVIEN;

GRANT SELECT ON COURSEMAN.SINH_VIEN TO SINHVIEN;
GRANT SELECT ON COURSEMAN.GIAO_VU TO GIAOVU;
GRANT SELECT ON COURSEMAN.GIAO_VIEN TO GIAOVU;
GRANT SELECT ON COURSEMAN.SINH_VIEN TO GIAOVU;
GRANT SELECT ON COURSEMAN.GIAO_VIEN TO GIAOVIEN;
GRANT SELECT ON COURSEMAN.SINH_VIEN TO GIAOVIEN;

GRANT TRUONGPHOKHOA TO CE_VOBICHXA, CE_NGUYENKIMXA;
GRANT TRUONGBOMON TO CE_HODONGXA, CE_LEXUANAN, CE_TRANHANHUNG, CE_DUONGBAMAO, CE_BUIMANHAN;

CREATE OR REPLACE VIEW VIEW_BO_MON_KHOA AS
SELECT * FROM COURSEMAN.BO_MON
WHERE MA_KHOA = (
    SELECT k.MA_KHOA FROM COURSEMAN.KHOA k
    JOIN COURSEMAN.NGUOI_DUNG nd ON nd.MA_ND = k.MA_TPK
    WHERE nd.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
) WITH CHECK OPTION;

CREATE OR REPLACE VIEW VIEW_BO_MON_KHOA_INSERT AS
SELECT MA_KHOA, MA_TBM, TEN_BO_MON FROM COURSEMAN.BO_MON
WHERE MA_KHOA = (
    SELECT k.MA_KHOA FROM COURSEMAN.KHOA k
    JOIN COURSEMAN.NGUOI_DUNG nd ON nd.MA_ND = k.MA_TPK
    WHERE nd.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
) WITH CHECK OPTION;

CREATE OR REPLACE VIEW VIEW_MON_HOC_BO_MON AS
SELECT * FROM COURSEMAN.MON_HOC
WHERE MA_BO_MON = (
    SELECT bm.MA_BO_MON FROM COURSEMAN.BO_MON bm
    JOIN COURSEMAN.NGUOI_DUNG nd ON nd.MA_ND = bm.MA_TBM
    WHERE nd.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
) OR MA_BO_MON IN (
  SELECT MA_BO_MON FROM VIEW_BO_MON_KHOA
);

CREATE OR REPLACE VIEW VIEW_MON_HOC_BO_MON_INSERT AS
SELECT MA_BO_MON, TEN_MON_HOC FROM COURSEMAN.MON_HOC
WHERE MA_BO_MON = (
    SELECT bm.MA_BO_MON FROM COURSEMAN.BO_MON bm
    JOIN COURSEMAN.NGUOI_DUNG nd ON nd.MA_ND = bm.MA_TBM
    WHERE nd.USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
) OR MA_BO_MON IN (
  SELECT MA_BO_MON FROM VIEW_BO_MON_KHOA
);

CREATE OR REPLACE VIEW VIEW_KHOA_LAM_TPK AS
SELECT * FROM COURSEMAN.KHOA
WHERE MA_TPK = (
  SELECT MA_ND FROM NGUOI_DUNG
  WHERE USERNAME = SYS_CONTEXT('USERENV', 'SESSION_USER')
);

GRANT SELECT, UPDATE, DELETE ON COURSEMAN.VIEW_BO_MON_KHOA TO TRUONGPHOKHOA;
GRANT SELECT ON COURSEMAN.VIEW_KHOA_LAM_TPK TO TRUONGPHOKHOA;
GRANT INSERT ON COURSEMAN.VIEW_BO_MON_KHOA_INSERT TO TRUONGPHOKHOA;
GRANT SELECT, UPDATE, DELETE ON COURSEMAN.VIEW_MON_HOC_BO_MON TO TRUONGPHOKHOA;
GRANT INSERT ON COURSEMAN.VIEW_MON_HOC_BO_MON_INSERT TO TRUONGPHOKHOA;
GRANT SELECT ON COURSEMAN.VIEW_MON_HOC_BO_MON TO TRUONGBOMON;

CREATE OR REPLACE VIEW VIEW_LICH_MON_HOC AS
SELECT mh.TEN_MON_HOC, lh.* FROM COURSEMAN.LICH_HOC lh
JOIN MON_HOC_MO mhm ON mhm.MA_MON_HOC_MO = lh.MA_MON_HOC_MO
JOIN MON_HOC mh ON mh.MA_MON_HOC = mhm.MA_MON_HOC;

CREATE OR REPLACE VIEW VIEW_SINH_VIEN_DIEM AS
SELECT mh.TEN_MON_HOC, dk.* FROM COURSEMAN.DANG_KY dk
JOIN MON_HOC_MO mhm ON mhm.MA_MON_HOC_MO = dk.MA_MON_HOC_MO
JOIN MON_HOC mh ON mh.MA_MON_HOC = mhm.MA_MON_HOC;

GRANT SELECT ON VIEW_SINH_VIEN_DIEM TO SINHVIEN;

